-- Схема Supabase для «Учебного навигатора» (блок С2).
-- Выполнить целиком в Supabase Dashboard → SQL Editor до запуска мигратора.
-- Повторный запуск безопасен: таблицы, индексы и функция создаются идемпотентно.

create table if not exists public.teachers (
    id bigint generated by default as identity primary key,
    name text,
    subject text,
    school text,
    telegram_user_id bigint unique,
    created_at timestamptz default current_timestamp
);

create table if not exists public.style_profiles (
    id bigint generated by default as identity primary key,
    teacher_id bigint references public.teachers(id),
    goal_phrasing text,
    stage_structure text,
    assessment_methods text,
    resources_used text,
    raw_samples_count integer,
    updated_at timestamptz
);

create table if not exists public.templates (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    source text,
    is_official integer not null default 0 check (is_official in (0, 1)),
    is_builtin integer not null default 0 check (is_builtin in (0, 1)),
    category text not null default 'personal' check (category in ('official', 'sample', 'personal')),
    uploaded_by bigint references public.teachers(id),
    structure_json text not null,
    created_at timestamptz default current_timestamp
);

create table if not exists public.template_selections (
    telegram_user_id bigint primary key,
    template_id bigint not null references public.templates(id),
    selected_at timestamptz not null
);

create table if not exists public.curriculum_objectives (
    code text primary key,
    grade integer,
    section text,
    subsection text,
    description text,
    thinking_level text
);

create table if not exists public.ktp_entries (
    id bigint generated by default as identity primary key,
    teacher_id bigint references public.teachers(id),
    lesson_number integer,
    section text,
    topic text,
    objective_code text references public.curriculum_objectives(code),
    hours integer,
    planned_date text,
    quarter integer
);

create table if not exists public.generated_ksp (
    id text primary key,
    teacher_id bigint references public.teachers(id),
    ktp_entry_id bigint references public.ktp_entries(id),
    template_id bigint references public.templates(id),
    content_json text,
    docx_path text,
    created_at timestamptz default current_timestamp
);

create table if not exists public.tasks (
    id text primary key,
    -- 'sverka_tetradi' добавлен блоком У4 (PLAN.md). ⚠️ CREATE TABLE IF NOT
    -- EXISTS не меняет CHECK уже существующей таблицы — на прод, где
    -- tasks уже есть, это применяется отдельным ALTER TABLE через SQL
    -- Editor (готовый SQL — в отчёте по блоку У4), не автоматическим
    -- перезапуском этого файла.
    type text check (type in ('parse_ksp', 'generate_ksp', 'generate_ktp', 'transcribe', 'generate_konspekt', 'sverka_tetradi')),
    status text check (status in ('pending', 'processing', 'done', 'failed')) default 'pending',
    payload text,
    result text,
    error text,
    telegram_chat_id bigint,
    retries integer default 0,
    created_at timestamptz default current_timestamp,
    updated_at timestamptz
);

create table if not exists public.usage_daily (
    telegram_user_id bigint not null,
    day text not null,
    operation text not null,
    count integer not null default 0,
    tokens integer not null default 0,
    primary key (telegram_user_id, day, operation)
);

create table if not exists public.admin_access (
    telegram_user_id bigint primary key,
    expires_at text not null
);

create table if not exists public.transcripts (
    id text primary key,
    teacher_id bigint references public.teachers(id),
    ktp_entry_id bigint references public.ktp_entries(id),
    source text,
    mode text not null default 'student' check (mode in ('student', 'teacher')),
    text text not null,
    duration_seconds integer,
    language text,
    created_at timestamptz default current_timestamp
);

create table if not exists public.konspekty (
    id text primary key,
    teacher_id bigint references public.teachers(id),
    transcript_id text references public.transcripts(id),
    mode text not null default 'student' check (mode in ('student', 'teacher')),
    ktp_entry_id bigint references public.ktp_entries(id),
    tema text,
    content_json text not null,
    docx_path text,
    created_at timestamptz default current_timestamp
);

create table if not exists public.incidents (
    id bigint generated by default as identity primary key,
    started_at timestamptz not null,
    ended_at timestamptz,
    reason text not null,
    notified integer not null default 0
);

create table if not exists public.worker_heartbeat (
    id integer primary key check (id = 1),
    updated_at timestamptz not null default current_timestamp
);

-- consents — согласие на использование системы (блок Ю3, storage/schema.sql
-- несёт полное обоснование, почему отдельная таблица, а не колонка в
-- teachers). ⚠️ Эта таблица создаётся в проде только вручную через SQL
-- Editor — RPC ksp_execute_sql намеренно не пропускает DDL (см. комментарий
-- к функции ниже), автоматически применить эту миграцию нельзя.
create table if not exists public.consents (
    telegram_user_id bigint primary key,
    given_at timestamptz not null
);

-- classes/students/class_members — класс и ученики (блок У1, MASTER.md
-- 0.9 п.2; storage/schema.sql несёт полное обоснование формы таблиц).
-- ⚠️ Как и consents выше, эти три таблицы создаются в проде только
-- вручную через SQL Editor — RPC ksp_execute_sql не пропускает DDL (см.
-- комментарий к функции ниже). Готовый SQL — в отчёте по блоку У1.
create table if not exists public.classes (
    id bigint generated by default as identity primary key,
    teacher_id bigint not null references public.teachers(id),
    name text not null,
    subject text,
    invite_code text not null,
    created_at timestamptz default current_timestamp
);

create table if not exists public.students (
    id bigint generated by default as identity primary key,
    telegram_id bigint not null,
    name text,
    joined_at timestamptz default current_timestamp
);

create table if not exists public.class_members (
    id bigint generated by default as identity primary key,
    class_id bigint not null references public.classes(id),
    student_id bigint not null references public.students(id),
    joined_at timestamptz default current_timestamp
);

create unique index if not exists idx_classes_invite_code on public.classes(invite_code);
create unique index if not exists idx_students_telegram_id on public.students(telegram_id);
create unique index if not exists idx_class_members_unique on public.class_members(class_id, student_id);
create index if not exists idx_classes_teacher on public.classes(teacher_id);
create index if not exists idx_class_members_student on public.class_members(student_id);

create index if not exists idx_ktp_teacher on public.ktp_entries(teacher_id);
create index if not exists idx_tasks_status on public.tasks(status);
create index if not exists idx_incidents_unresolved on public.incidents(ended_at, notified);
create index if not exists idx_transcripts_teacher on public.transcripts(teacher_id);
create index if not exists idx_konspekty_teacher on public.konspekty(teacher_id);

-- Эта функция доступна только service_role. Она получает статический SQL из
-- core/db.py и отдельный массив значений; значения подставляются сервером
-- через quote_literal, а не конкатенируются клиентом.
create or replace function public.ksp_execute_sql(statement text, parameters jsonb default '[]'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    source text := btrim(statement);   -- исходный запрос, для проверок и выбора ветки
    compiled text := '';               -- собираемый слева направо результат
    remainder text;                    -- ещё не разобранный остаток исходного запроса
    parameter_value jsonb;
    replacement text;
    parameter_index integer;
    placeholder_position integer;
    rows jsonb := '[]'::jsonb;
    affected integer := 0;
begin
    if source = '' or source like '%;%' then
        raise exception 'Ожидается один SQL-запрос без точки с запятой';
    end if;
    if lower(source) !~ '^(select|with|insert|update|delete)[[:space:]]' then
        raise exception 'Разрешены только SELECT, WITH, INSERT, UPDATE и DELETE';
    end if;
    if jsonb_typeof(parameters) <> 'array' then
        raise exception 'parameters должен быть JSON-массивом';
    end if;

    remainder := source;
    if jsonb_array_length(parameters) > 0 then
        for parameter_index in 0 .. jsonb_array_length(parameters) - 1 loop
            placeholder_position := strpos(remainder, '?');
            if placeholder_position = 0 then
                raise exception 'Параметров больше, чем плейсхолдеров';
            end if;
            parameter_value := parameters -> parameter_index;
            if parameter_value = 'null'::jsonb then
                replacement := 'NULL';
            elsif jsonb_typeof(parameter_value) = 'string' then
                replacement := quote_literal(parameter_value #>> '{}');
            elsif jsonb_typeof(parameter_value) in ('number', 'boolean') then
                replacement := parameter_value #>> '{}';
            else
                replacement := quote_literal(parameter_value::text);
            end if;
            -- Ключевая правка (Находка 2 AUDIT.md): разобранное уходит в
            -- compiled и больше не просматривается, поиск следующего '?'
            -- идёт только по остатку. Знак вопроса ВНУТРИ значения
            -- параметра поэтому не может быть принят за плейсхолдер.
            compiled := compiled || substr(remainder, 1, placeholder_position - 1) || replacement;
            remainder := substr(remainder, placeholder_position + 1);
        end loop;
    end if;
    if strpos(remainder, '?') > 0 then
        raise exception 'Плейсхолдеров больше, чем параметров';
    end if;
    compiled := compiled || remainder;

    -- Ветка выбирается по ИСХОДНОМУ запросу: слово returning в значении
    -- параметра больше не может увести UPDATE в ветку WITH.
    if lower(source) ~ '^select[[:space:]]' then
        execute format('select coalesce(jsonb_agg(to_jsonb(result_row)), ''[]''::jsonb) from (%s) result_row', compiled)
            into rows;
        affected := jsonb_array_length(rows);
    elsif lower(source) ~ '^with[[:space:]]' or lower(source) ~ '[[:space:]]returning[[:space:]]' then
        execute format('with result_row as (%s) select coalesce(jsonb_agg(to_jsonb(result_row)), ''[]''::jsonb) from result_row', compiled)
            into rows;
        affected := jsonb_array_length(rows);
    elsif lower(source) ~ '^insert[[:space:]]' then
        execute format('with result_row as (%s returning *) select coalesce(jsonb_agg(to_jsonb(result_row)), ''[]''::jsonb) from result_row', compiled)
            into rows;
        affected := jsonb_array_length(rows);
    else
        execute compiled;
        get diagnostics affected = row_count;
    end if;
    return jsonb_build_object('rows', rows, 'rowcount', affected);
end;
$$;

revoke all on function public.ksp_execute_sql(text, jsonb) from public, anon, authenticated;
grant execute on function public.ksp_execute_sql(text, jsonb) to service_role;
